name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1          
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: deploy
        run: |
          npm i -g @vercel/ncc
          npx ncc build  create-short-url.ts --out dist/create-short-url
          npx ncc build  get-full-url.ts --out dist/get-full-url
          zip -j create-short-url.zip ./dist/create-short-url/*
          zip -j get-full-url.zip ./dist/get-full-url/*
          aws lambda update-function-code --function-name=get-full-url --zip-file=fileb://get-full-url.zip
          aws lambda update-function-code --function-name=create-short-url --zip-file=fileb://create-short-url.zip